export const mockDashboardStats = {
  totalJobs: 6,
  activeJobs: 4,
  totalCandidates: 34,
  candidatesAnalyzed: 29,
  interviewsPending: 8,
  evaluationsCompleted: 15,
  evidenceVerifiedRate: "82%",
};

export const mockRecentCandidates = [
  {
    id: "c-101",
    name: "Alex Rivera",
    email: "alex.rivera@example.com",
    role: "Senior Backend Engineer",
    experienceYears: 6.5,
    appliedDate: "2026-09-17",
    status: "Analyzed",
    evidenceFoundCount: 7,
    missingInfoCount: 1,
    requiresValidationCount: 2,
    skills: ["Python", "FastAPI", "PostgreSQL", "Docker", "Redis"],
    topEvidence: "Led microservice architecture migration handling 15k req/sec with FastAPI and Kafka.",
    overallAssessment: "Strong technical alignment; recruiter interview needed to validate team leadership scope.",
  },
  {
    id: "c-102",
    name: "Priya Sharma",
    email: "priya.s@example.com",
    role: "Full Stack AI Engineer",
    experienceYears: 4.0,
    appliedDate: "2026-09-18",
    status: "Interview Scheduled",
    evidenceFoundCount: 6,
    missingInfoCount: 2,
    requiresValidationCount: 1,
    skills: ["React", "TypeScript", "Python", "LangChain", "Vector DBs"],
    topEvidence: "Built RAG retrieval pipeline with Pinecone and FastAPI; React frontend with Tailwind.",
    overallAssessment: "Solid LLM tooling exposure; needs verification on production deployment practices.",
  },
  {
    id: "c-103",
    name: "Marcus Chen",
    email: "m.chen@example.com",
    role: "Staff DevOps Engineer",
    experienceYears: 8.0,
    appliedDate: "2026-09-16",
    status: "Evaluation Ready",
    evidenceFoundCount: 8,
    missingInfoCount: 0,
    requiresValidationCount: 1,
    skills: ["Kubernetes", "Terraform", "AWS", "CI/CD", "Prometheus"],
    topEvidence: "Architected multi-region EKS deployment with automated zero-downtime rollouts.",
    overallAssessment: "High evidence match on infrastructure criteria; recruiter review pending.",
  },
  {
    id: "c-104",
    name: "Sofia Rodriguez",
    email: "sofia.r@example.com",
    role: "Frontend Lead",
    experienceYears: 5.5,
    appliedDate: "2026-09-18",
    status: "Screening Pending",
    evidenceFoundCount: 5,
    missingInfoCount: 3,
    requiresValidationCount: 2,
    skills: ["React", "Next.js", "Design Systems", "Web Performance"],
    topEvidence: "Created accessible enterprise UI library adopted by 20+ squads.",
    overallAssessment: "Frontend architecture is well-evidenced; backend collaboration details are unclear in CV.",
  },
];

export const mockRecentActivity = [
  {
    id: "act-1",
    type: "ANALYSIS_COMPLETE",
    title: "AI Analysis Completed",
    description: "Extracted 7 verified evidence points for Alex Rivera (Senior Backend Engineer).",
    timestamp: "25 minutes ago",
    badge: "Evidence Mapped",
    badgeColor: "emerald",
  },
  {
    id: "act-2",
    type: "EVALUATION_GENERATED",
    title: "Interview Evaluation Ready",
    description: "Structured interview summary generated for Marcus Chen. Awaiting recruiter sign-off.",
    timestamp: "1 hour ago",
    badge: "Action Needed",
    badgeColor: "amber",
  },
  {
    id: "act-3",
    type: "RESUMES_UPLOADED",
    title: "Batch Resumes Uploaded",
    description: "6 new resumes parsed for Full Stack AI Engineer position.",
    timestamp: "3 hours ago",
    badge: "Batch Process",
    badgeColor: "blue",
  },
  {
    id: "act-4",
    type: "JOB_POSTED",
    title: "New Job Requirements Defined",
    description: "Created Senior Platform Engineer job with 8 required competencies.",
    timestamp: "Yesterday",
    badge: "Job Active",
    badgeColor: "purple",
  },
];

export const mockJobs = [
  {
    id: "job-1",
    title: "Senior Backend Engineer",
    department: "Engineering",
    location: "Remote / Hybrid",
    status: "Active",
    candidatesCount: 14,
    requiredSkills: ["Python", "FastAPI", "PostgreSQL", "System Design", "Microservices"],
    experienceMin: "5+ years",
    education: "B.S. in Computer Science or equivalent practical experience",
    createdAt: "2026-09-10",
  },
  {
    id: "job-2",
    title: "Full Stack AI Engineer",
    department: "AI Products",
    location: "San Francisco, CA (or Remote)",
    status: "Active",
    candidatesCount: 12,
    requiredSkills: ["React", "TypeScript", "Python", "LLMs", "Vector Databases"],
    experienceMin: "3+ years",
    education: "Degree in STEM or equivalent portfolio",
    createdAt: "2026-09-14",
  },
  {
    id: "job-3",
    title: "Staff DevOps Engineer",
    department: "Infrastructure",
    location: "Remote",
    status: "Active",
    candidatesCount: 8,
    requiredSkills: ["Kubernetes", "Terraform", "AWS", "Observability"],
    experienceMin: "7+ years",
    education: "Not required; production track record preferred",
    createdAt: "2026-09-12",
  },
];
