import os
import smtplib
import logging
import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.application import MIMEApplication
from typing import Dict, Any, Optional

from app.core.config import settings

logger = logging.getLogger("hireflow.email")


class EmailService:
    @staticmethod
    def is_configured() -> bool:
        """Check if SMTP credentials are provided."""
        return bool(
            settings.SMTP_HOST
            and settings.SMTP_USERNAME
            and settings.SMTP_PASSWORD
            and settings.SMTP_USERNAME.strip()
            and settings.SMTP_PASSWORD.strip()
        )

    @classmethod
    def send_candidate_evaluation_report(
        cls,
        recipient_email: str,
        candidate_name: str,
        job_role: str,
        pdf_bytes: bytes,
        filename: Optional[str] = None,
        custom_message: Optional[str] = None,
        subject: Optional[str] = None,
    ) -> Dict[str, Any]:
        """
        Send an evaluation report PDF to the candidate with an enterprise HTML template.
        Supports both live SMTP delivery and safe audit simulation when credentials are unset.
        """
        if not recipient_email or "@" not in recipient_email:
            raise ValueError(f"Invalid recipient email address: '{recipient_email}'")

        if not filename:
            clean_name = candidate_name.replace(" ", "_")
            filename = f"HireFlow_Evaluation_Report_{clean_name}.pdf"

        if not subject:
            subject = f"Evaluation Report - {candidate_name} | {job_role}"

        from_header = f"{settings.EMAIL_FROM_NAME} <{settings.EMAIL_FROM}>"

        default_note = (
            f"Thank you for participating in our technical screening and interview process for the "
            f"<strong>{job_role}</strong> role. Please find attached your comprehensive evaluation report "
            f"summarizing the evidence, requirements validation, and recruiter synthesis."
        )
        recruiter_note_html = (
            f"<p style='background-color: #F8FAFC; border-left: 4px solid #0284C7; padding: 12px 16px; margin: 16px 0; color: #334155; font-style: italic;'>"
            f"\"{custom_message.strip()}\"</p>"
            if custom_message and custom_message.strip()
            else ""
        )

        html_body = f"""<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{subject}</title>
</head>
<body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; background-color: #F1F5F9; margin: 0; padding: 24px; color: #0F172A;">
  <div style="max-width: 600px; margin: 0 auto; background-color: #FFFFFF; border-radius: 8px; border: 1px solid #E2E8F0; overflow: hidden; box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.05);">
    <div style="background-color: #0284C7; padding: 24px 32px; color: #FFFFFF;">
      <p style="margin: 0 0 4px 0; font-size: 11px; font-weight: 700; letter-spacing: 0.1em; text-transform: uppercase; color: #BAE6FD;">HireFlow Recruitment</p>
      <h1 style="margin: 0; font-size: 20px; font-weight: 700;">Candidate Evaluation Report</h1>
    </div>
    
    <div style="padding: 32px;">
      <p style="font-size: 15px; line-height: 1.6; margin-top: 0; color: #1E293B;">
        Dear <strong>{candidate_name}</strong>,
      </p>
      <p style="font-size: 14px; line-height: 1.6; color: #334155;">
        {default_note}
      </p>

      {recruiter_note_html}

      <div style="margin: 24px 0; padding: 16px; background-color: #F8FAFC; border: 1px solid #E2E8F0; border-radius: 6px;">
        <div style="display: flex; align-items: center; justify-content: space-between;">
          <span style="font-size: 13px; font-weight: 600; color: #0F172A;">Attachment:</span>
          <span style="font-size: 12px; font-weight: 500; color: #0284C7; background-color: #E0F2FE; padding: 2px 8px; border-radius: 4px;">PDF Document</span>
        </div>
        <p style="margin: 6px 0 0 0; font-size: 13px; color: #475569; font-family: monospace;">
          {filename} ({len(pdf_bytes) // 1024} KB)
        </p>
      </div>

      <p style="font-size: 13px; line-height: 1.6; color: #64748B;">
        If you have any questions or require additional details regarding this evaluation, please reach out to your designated recruitment coordinator.
      </p>

      <p style="font-size: 14px; line-height: 1.6; color: #1E293B; margin-bottom: 0;">
        Warm regards,<br>
        <strong>{settings.EMAIL_FROM_NAME}</strong>
      </p>
    </div>

    <div style="background-color: #F8FAFC; border-top: 1px solid #E2E8F0; padding: 16px 32px; font-size: 11px; color: #94A3B8; text-align: center;">
      This evaluation report is strictly confidential. &bull; Generated by HireFlow Evidence-Based Recruitment Platform
    </div>
  </div>
</body>
</html>"""

        plain_text = (
            f"Dear {candidate_name},\n\n"
            f"Thank you for participating in our technical screening and interview process for the {job_role} role. "
            f"Please find attached your comprehensive evaluation report.\n\n"
            + (f"Recruiter Note:\n{custom_message.strip()}\n\n" if custom_message else "")
            + f"Attachment: {filename}\n\n"
            f"Warm regards,\n"
            f"{settings.EMAIL_FROM_NAME}"
        )

        # Create MIME Multipart Message
        msg = MIMEMultipart("mixed")
        msg["Subject"] = subject
        msg["From"] = from_header
        msg["To"] = recipient_email
        msg["Date"] = datetime.datetime.utcnow().strftime("%a, %d %b %Y %H:%M:%S +0000")

        msg_body = MIMEMultipart("alternative")
        msg_body.attach(MIMEText(plain_text, "plain", "utf-8"))
        msg_body.attach(MIMEText(html_body, "html", "utf-8"))
        msg.attach(msg_body)

        # Attach PDF
        pdf_attachment = MIMEApplication(pdf_bytes, _subtype="pdf")
        pdf_attachment.add_header("Content-Disposition", "attachment", filename=filename)
        msg.attach(pdf_attachment)

        sent_timestamp = datetime.datetime.utcnow().isoformat()

        # Send via SMTP or Simulate
        if cls.is_configured():
            try:
                logger.info(f"Connecting to SMTP server {settings.SMTP_HOST}:{settings.SMTP_PORT}...")
                with smtplib.SMTP(settings.SMTP_HOST, settings.SMTP_PORT, timeout=15) as server:
                    if settings.SMTP_USE_TLS:
                        server.starttls()
                    server.login(settings.SMTP_USERNAME, settings.SMTP_PASSWORD)
                    server.send_message(msg)

                logger.info(f"Successfully delivered evaluation report email to {recipient_email}")
                return {
                    "success": True,
                    "mode": "live_smtp",
                    "recipient": recipient_email,
                    "sent_at": sent_timestamp,
                    "message": f"Evaluation report email sent successfully to {recipient_email}.",
                }
            except Exception as e:
                logger.error(f"Failed to send email via SMTP to {recipient_email}: {str(e)}")
                return {
                    "success": False,
                    "mode": "live_smtp",
                    "recipient": recipient_email,
                    "error": f"SMTP Delivery Failed: {str(e)}",
                }
        else:
            # Simulated delivery for development / demo when SMTP credentials are not configured
            logger.info(
                f"[EMAIL SIMULATION] SMTP credentials not set in .env. "
                f"Simulating successful email dispatch to {recipient_email} with PDF '{filename}' ({len(pdf_bytes)} bytes)."
            )
            return {
                "success": True,
                "mode": "simulated",
                "recipient": recipient_email,
                "sent_at": sent_timestamp,
                "message": (
                    f"Evaluation report dispatched successfully to {recipient_email}. "
                    f"(Development Mode: Simulated delivery recorded)"
                ),
            }


email_service = EmailService()
